
FROM alpine:3.17.0 as build_stage


WORKDIR /migrations

RUN apk update && \
    apk upgrade && \
    apk add bash && \
    rm -rf /var/cache/apk/*

ADD https://github.com/pressly/goose/releases/download/v3.7.0/goose_linux_x86_64 /bin/goose
RUN chmod +x /bin/goose

ARG DB_URL

ENV DB_URL=${DB_URL}

